In [4]:
# Importando RASD Toolbox
from RASD_TOOLBOX import *
# Importando Numpy toolbox
import numpy as np
import pandas as pd
from VIGA_METALICA_VERIFICA import *
from FINITO_FEM_TOOLBOX import *
from datetime import datetime

In [75]:
DADOS = pd.read_csv('arquivos/COM ISE.txt', sep=";") #importar dataframe

In [76]:
DADOS

,# X_0,X_1,X_2,X_3,X_4,X_5,X_6,X_7,X_8,X_9,...,I_5,I_6,I_7,I_8,I_9,I_10,I_11,I_12,I_13,I_14
0,2.016798e+11,2.673880e+08,15298.21031,1.04716,1.00861,133.10400,5.72480,91.67554,7.10751,2719.12094,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.996928e+11,2.261469e+08,14220.46548,1.03198,0.92643,130.78416,5.69103,104.12401,7.38223,2012.23262,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1.936529e+11,2.399757e+08,15610.49387,1.01392,1.00645,136.68697,5.75827,103.20249,7.17129,2188.71600,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.816937e+11,2.378212e+08,11870.96073,0.99516,0.97786,145.95678,5.89025,96.59971,7.00324,2824.22614,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1.891672e+11,2.507602e+08,12703.96872,0.99796,1.03452,139.62780,5.73218,107.54695,7.65890,346.85759,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,1.931694e+11,2.811189e+08,11921.68537,0.98697,0.99895,145.73571,5.33578,104.97763,6.87725,1766.81562,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
99996,1.911289e+11,2.475776e+08,13761.61359,0.96662,1.00038,134.93687,5.95713,107.25340,6.78123,4519.18891,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
99997,1.966049e+11,2.451698e+08,11443.69199,0.95244,1.04286,152.60575,5.87607,101.13841,7.05962,2655.62590,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
99998,1.937862e+11,2.584826e+08,14536.63086,1.04731,1.04985,148.43216,5.93906,97.47453,7.34319,2986.69162,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
99999,1.929788e+11,2.450610e+08,15042.48938,0.95910,1.01255,145.19946,5.80577,106.57240,6.57479,3586.63982,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [77]:
DADOS['S_10'] = DADOS['S_10']*100
DADOS['S_11'] = DADOS['S_11']*100
DADOS['S_12'] = DADOS['S_12']*100
DADOS['S_13'] = DADOS['S_13']*100
DADOS['S_14'] = DADOS['S_14']*100

In [78]:
DADOS['S_10']

0        0.255
1        0.222
2        0.253
3        0.223
4        0.221
         ...
99995    0.218
99996    0.255
99997    0.232
99998    0.260
99999    0.260
Name: S_10, Length: 100000, dtype: float64

In [79]:
DADOS['R_10']

0        0.01571
1        0.01548
2        0.01521
3        0.01493
4        0.01497
          ...
99995    0.01480
99996    0.01450
99997    0.01429
99998    0.01571
99999    0.01439
Name: R_10, Length: 100000, dtype: float64

In [80]:
DADOS['R_10'] - DADOS['S_10']

0       -0.23929
1       -0.20652
2       -0.23779
3       -0.20807
4       -0.20603
          ...
99995   -0.20320
99996   -0.24050
99997   -0.21771
99998   -0.24429
99999   -0.24561
Length: 100000, dtype: float64

In [81]:
DADOS.loc[DADOS['R_10'] - DADOS['S_10'] < 0 , 'I_10'] = 1
DADOS.loc[DADOS['R_11'] - DADOS['S_11'] < 0 , 'I_11'] = 1
DADOS.loc[DADOS['R_12'] - DADOS['S_12'] < 0 , 'I_12'] = 1
DADOS.loc[DADOS['R_13'] - DADOS['S_13'] < 0 , 'I_13'] = 1
DADOS.loc[DADOS['R_14'] - DADOS['S_14'] < 0 , 'I_14'] = 1

In [82]:
DADOS['I_10'].sum()

100000.0

In [83]:
DADOS['I_12'].sum()

100000.0

In [95]:
DADOS

,# X_0,X_1,X_2,X_3,X_4,X_5,X_6,X_7,X_8,X_9,...,I_5,I_6,I_7,I_8,I_9,I_10,I_11,I_12,I_13,I_14
0,2.016798e+11,2.673880e+08,15298.21031,1.04716,1.00861,133.10400,5.72480,91.67554,7.10751,2719.12094,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0
1,1.996928e+11,2.261469e+08,14220.46548,1.03198,0.92643,130.78416,5.69103,104.12401,7.38223,2012.23262,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0
2,1.936529e+11,2.399757e+08,15610.49387,1.01392,1.00645,136.68697,5.75827,103.20249,7.17129,2188.71600,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0
3,1.816937e+11,2.378212e+08,11870.96073,0.99516,0.97786,145.95678,5.89025,96.59971,7.00324,2824.22614,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0
4,1.891672e+11,2.507602e+08,12703.96872,0.99796,1.03452,139.62780,5.73218,107.54695,7.65890,346.85759,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,1.931694e+11,2.811189e+08,11921.68537,0.98697,0.99895,145.73571,5.33578,104.97763,6.87725,1766.81562,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0
99996,1.911289e+11,2.475776e+08,13761.61359,0.96662,1.00038,134.93687,5.95713,107.25340,6.78123,4519.18891,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0
99997,1.966049e+11,2.451698e+08,11443.69199,0.95244,1.04286,152.60575,5.87607,101.13841,7.05962,2655.62590,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0
99998,1.937862e+11,2.584826e+08,14536.63086,1.04731,1.04985,148.43216,5.93906,97.47453,7.34319,2986.69162,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0
99999,1.929788e+11,2.450610e+08,15042.48938,0.95910,1.01255,145.19946,5.80577,106.57240,6.57479,3586.63982,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0

In [108]:
HEADER_NAMES1 = ("X_0";"X_1";"X_2";"X_3";"X_4";"X_5";"X_6";"X_7";"X_8";"X_9";"I_5";"I_6";"I_7";"I_8";"I_9";"I_10";"I_11";"I_12";"I_13";"I_14")
#HEADER_NAMES1 = ["X_0","X_1","X_2","X_3","X_4","X_5","X_6","X_7","X_8","X_9","I_5","I_6","I_7","I_8","I_9","I_10","I_11","I_12","I_13","I_14"]
#HEADER_NAMES2 =  ';'.join(HEADER_NAMES1)

SyntaxError: invalid syntax (<ipython-input-108-c69c2db4db7a>, line 1)

In [104]:
np.savetxt("NAME.txt", DADOS, fmt = '%1.5f', delimiter = ';' , header = HEADER_NAMES1)

AttributeError: 'list' object has no attribute 'replace'