In [4]:
# Importando RASD Toolbox
from RASD_TOOLBOX import *
# Importando Numpy toolbox
import numpy as np
import pandas as pd
from VIGA_METALICA_VERIFICA import *
from FINITO_FEM_TOOLBOX import *
from datetime import datetime

In [65]:
DADOS = pd.read_csv('arquivos - beta/COM ISE.txt', sep=";") #importar dataframe

In [74]:
DADOS

,# X_0,X_1,X_2,X_3,X_4,X_5,X_6,X_7,X_8,X_9,...,I_5,I_6,I_7,I_8,I_9,I_10,I_11,I_12,I_13,I_14
0,2.020405e+11,2.417182e+08,13670.09535,0.99352,0.97809,140.89041,6.46124,100.80455,7.57591,2330.37165,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2.190121e+11,2.383516e+08,16334.67047,1.01348,0.97778,136.08809,5.26364,107.16595,7.57010,1801.10806,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2.113530e+11,2.561004e+08,13419.64081,1.02466,0.92256,142.39917,5.58692,101.35908,6.93812,1945.89616,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2.206510e+11,2.385581e+08,11932.59650,1.01942,1.04668,144.76736,5.62509,109.15354,6.87642,1669.27930,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2.049631e+11,2.841880e+08,13160.23595,1.02327,0.98753,148.73099,6.60036,113.85705,7.44303,1964.58938,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,1.999840e+11,2.640537e+08,13621.87704,0.97556,1.00653,132.31098,5.66385,95.51256,7.25560,1691.16827,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
99996,1.860487e+11,2.481613e+08,13309.88652,0.98538,1.01313,137.78648,5.86604,105.85916,6.83325,2889.91778,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
99997,1.803088e+11,2.487397e+08,14923.13560,0.99804,0.94278,141.60794,6.27000,107.20468,7.15696,2296.27544,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
99998,1.762713e+11,2.712127e+08,11281.50653,1.04067,1.05354,126.50194,5.69736,104.92224,7.16126,2519.60068,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
99999,2.092958e+11,2.725980e+08,12797.79846,1.01178,1.00787,136.65410,5.88247,97.20095,6.86236,2063.14679,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [43]:
DADOS['S_10'] = DADOS['S_10']*100
DADOS['S_11'] = DADOS['S_11']*100
DADOS['S_12'] = DADOS['S_12']*100
DADOS['S_13'] = DADOS['S_13']*100
DADOS['S_14'] = DADOS['S_14']*100

In [51]:
DADOS['S_10']

0        0.015
1        0.012
2        0.010
3        0.011
4        0.013
         ...
99995    0.010
99996    0.010
99997    0.015
99998    0.016
99999    0.011
Name: S_10, Length: 100000, dtype: float64

In [52]:
DADOS['R_10']

0        0.01506
1        0.01506
2        0.01500
3        0.01514
4        0.01508
          ...
99995    0.01457
99996    0.01518
99997    0.01476
99998    0.01438
99999    0.01467
Name: R_10, Length: 100000, dtype: float64

In [53]:
DADOS['R_10'] - DADOS['S_10']

0        1.004000
1        1.255000
2        1.500000
3        1.376364
4        1.160000
           ...
99995    1.457000
99996    1.518000
99997    0.984000
99998    0.898750
99999    1.333636
Length: 100000, dtype: float64

In [54]:
DADOS.loc[DADOS['R_10'] - DADOS['S_10'] < 0 , 'I_10'] = 1
DADOS.loc[DADOS['R_11'] - DADOS['S_11'] < 0 , 'I_11'] = 1
DADOS.loc[DADOS['R_12'] - DADOS['S_12'] < 0 , 'I_12'] = 1
DADOS.loc[DADOS['R_13'] - DADOS['S_13'] < 0 , 'I_13'] = 1
DADOS.loc[DADOS['R_14'] - DADOS['S_14'] < 0 , 'I_14'] = 1

In [55]:
DADOS['I_10'].sum()

14120.0

In [57]:
DADOS['I_12'].sum()

14120.0